apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gabesite-web
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gabesite-web-ip
  labels:
    app: gabesite
spec:
  backend:
    serviceName: gabesite-web-backend
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gabesite-web-backend
  labels:
    app: gabesite
spec:
  type: NodePort
  selector:
    app: gabesite
    tier: web
  ports:
  - port: 8080
    targetPort: 8080